name: "Bug: Translation App"
description: When the translation App doesn't work as expected
title: "[Bug]: Translation App"
labels: ["translation app", "bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Here are some usecases when you should use this template :
        - Receive an unexpected error from the Translation App
        - Translation App cannot start properly
        - Buttons/Actions are not working as expected
        
  - type: dropdown
    id: browsers
    attributes:
      label: What Tales of Game are you working on?
      multiple: false
      options:
        - Tales of Rebirth (PS2)
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord name
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

