name: "Bug: Game Patch"
description: When an issue is encountered using a specific patch
title: "[Bug]: Your short description here"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Here are some usecases when you should use this template :
        - Emulator crashes
        - Game freezes for no reason
        - Graphic glitch 
        - Text borked
        - Game skip a scene for no reason
        
  - type: dropdown
    id: browsers
    attributes:
      label: What Tales of Game are you working on?
      multiple: false
      options:
        - Tales of Rebirth (PS2)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version details
      description: What version of the patch are you using? 
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord name
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

