name: Build App
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
       
    # Install .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7'
 
    - name: Build and Publish App
      run: msbuild TranslationApp.sln /p:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_app
        path: TranslationApp\bin\Release\
