
name: test

on: [push]

env:
  base_directory: c:/actions-runner/_work/PythonLib/

jobs:

  startVM:
    runs-on: ubuntu-latest
    steps:
    
    #Test againworki
    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm start -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}

  pythonCode:
    runs-on: self-hosted
    
    needs: startVM
    steps:
    
    - name: Checkout Pythonlib repo
      uses: actions/checkout@v2
      with:
        repository: lifebottle/PythonLib

    - name: Checkout TOR Repo
      uses: actions/checkout@v2
      with:
        repository: SymphoniaLauren/Tales-of-Rebirth

    - name: Extract DAT.bin
      working-directory: ${{env.base_directory}}
      run: 
        python ${{env.base_directory}}/ToolsTales_Executable.py --game TOR unpack Main 

    - name: Extract Menu Files
      working-directory: ${{env.base_directory}}
      run: 
        python ${{env.base_directory}}/ToolsTales_Executable.py --game TOR unpack Menu
          
  closeVM:
    runs-on: ubuntu-latest
    needs: pythonCode
    steps:

    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm stop -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}
        
    
    
